export interface DirectiveConfig {
  audienceDirective: string;
  autoincDirective: string;
  createdAtDirective: string;
  createDirective: string;
  createNestedDirective: string;
  defaultDirective: string;
  deleteDirective: string;
  derivedDirective: string;
  floatRangeDirective: string;
  generatedDefaultDirective: string;
  idDirective: string;
  idRefDirective: string;
  immutableDirective: string;
  intRangeDirective: string;
  lengthDirective: string;
  mutationDirective: string;
  newManyToManyDirective: string;
  oneToManyDirective: string;
  randomIdDirective: string;
  randomIdRefDirective: string;
  readonlyDirective: string;
  regexDirective: string;
  restoreDirective: string;
  softDeleteDirective: string;
  sqlColumnDirective: string;
  sqlTableDirective: string;
  sqlTypeDirective: string;
  sqlValueDirective: string;
  sqlValuesDirective: string;
  typeDiscriminatorDirective: string;
  uniqueDirective: string;
  unorderedDirective: string;
  updatedAtDirective: string;
  updateDirective: string;
  updateNestedDirective: string;
  updateOnlyDirective: string;
  useManyToManyDirective: string;
  wkidDirective: string;
  wkidRefDirective: string;
}

export const defaultConfig: DirectiveConfig = {
  audienceDirective: 'audience',
  autoincDirective: 'autoinc',
  createdAtDirective: 'createdAt',
  createDirective: 'create',
  createNestedDirective: 'createNested',
  defaultDirective: 'default',
  deleteDirective: 'delete',
  derivedDirective: 'derived',
  floatRangeDirective: 'floatRange',
  generatedDefaultDirective: 'generatedDefault',
  idDirective: 'id',
  idRefDirective: 'id',
  immutableDirective: 'immutable',
  intRangeDirective: 'intRange',
  lengthDirective: 'length',
  mutationDirective: 'mutation',
  newManyToManyDirective: 'newManyToMany',
  oneToManyDirective: 'oneToMany',
  randomIdDirective: 'rid',
  randomIdRefDirective: 'ridRef',
  readonlyDirective: 'readonly',
  regexDirective: 'regex',
  restoreDirective: 'restore',
  softDeleteDirective: 'softDelete',
  sqlColumnDirective: 'sqlColumn',
  sqlTableDirective: 'sqlTable',
  sqlTypeDirective: 'sqlType',
  sqlValueDirective: 'sqlValue',
  sqlValuesDirective: 'sqlValues',
  typeDiscriminatorDirective: 'typeDiscriminator',
  uniqueDirective: 'unique',
  unorderedDirective: 'unordered',
  updatedAtDirective: 'updatedAt',
  updateDirective: 'update',
  updateNestedDirective: 'updateNested',
  updateOnlyDirective: 'updateOnly',
  useManyToManyDirective: 'useManyToMany',
  wkidDirective: 'wkid',
  wkidRefDirective: 'wkidRef',
};
